(rulename) @function.builtin
(nonterminal) @type
(character) @string
(string) @string
(comment) @comment
(version) @comment
(hyphen) @punctuation.delimiter
(altsep) @punctuation.delimiter
(termsep) @punctuation.delimiter
(single_star) @punctuation.delimiter
(double_star) @punctuation.delimiter
(single_plus) @punctuation.delimiter
(double_plus) @punctuation.delimiter
(quest) @punctuation.delimiter
(osq) @punctuation.bracket
(csq) @punctuation.bracket
(op) @punctuation.bracket
(cp) @punctuation.bracket
(hex) @number
